# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Popochounet/Advanced_Cpp/B-CPP-500-LYN-5-1-rtype-basile.fouquet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Popochounet/Advanced_Cpp/B-CPP-500-LYN-5-1-rtype-basile.fouquet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Popochounet/Advanced_Cpp/B-CPP-500-LYN-5-1-rtype-basile.fouquet/CMakeFiles /home/Popochounet/Advanced_Cpp/B-CPP-500-LYN-5-1-rtype-basile.fouquet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Popochounet/Advanced_Cpp/B-CPP-500-LYN-5-1-rtype-basile.fouquet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shared_rtype

# Build rule for target.
shared_rtype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared_rtype
.PHONY : shared_rtype

# fast build rule for target.
shared_rtype/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_rtype.dir/build.make CMakeFiles/shared_rtype.dir/build
.PHONY : shared_rtype/fast

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/client/engine/ecs/ComponentSparseArray.o: src/client/engine/ecs/ComponentSparseArray.cpp.o
.PHONY : src/client/engine/ecs/ComponentSparseArray.o

# target to build an object file
src/client/engine/ecs/ComponentSparseArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/ComponentSparseArray.cpp.o
.PHONY : src/client/engine/ecs/ComponentSparseArray.cpp.o

src/client/engine/ecs/ComponentSparseArray.i: src/client/engine/ecs/ComponentSparseArray.cpp.i
.PHONY : src/client/engine/ecs/ComponentSparseArray.i

# target to preprocess a source file
src/client/engine/ecs/ComponentSparseArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/ComponentSparseArray.cpp.i
.PHONY : src/client/engine/ecs/ComponentSparseArray.cpp.i

src/client/engine/ecs/ComponentSparseArray.s: src/client/engine/ecs/ComponentSparseArray.cpp.s
.PHONY : src/client/engine/ecs/ComponentSparseArray.s

# target to generate assembly for a file
src/client/engine/ecs/ComponentSparseArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/ComponentSparseArray.cpp.s
.PHONY : src/client/engine/ecs/ComponentSparseArray.cpp.s

src/client/engine/ecs/Core.o: src/client/engine/ecs/Core.cpp.o
.PHONY : src/client/engine/ecs/Core.o

# target to build an object file
src/client/engine/ecs/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Core.cpp.o
.PHONY : src/client/engine/ecs/Core.cpp.o

src/client/engine/ecs/Core.i: src/client/engine/ecs/Core.cpp.i
.PHONY : src/client/engine/ecs/Core.i

# target to preprocess a source file
src/client/engine/ecs/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Core.cpp.i
.PHONY : src/client/engine/ecs/Core.cpp.i

src/client/engine/ecs/Core.s: src/client/engine/ecs/Core.cpp.s
.PHONY : src/client/engine/ecs/Core.s

# target to generate assembly for a file
src/client/engine/ecs/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Core.cpp.s
.PHONY : src/client/engine/ecs/Core.cpp.s

src/client/engine/ecs/Entity.o: src/client/engine/ecs/Entity.cpp.o
.PHONY : src/client/engine/ecs/Entity.o

# target to build an object file
src/client/engine/ecs/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Entity.cpp.o
.PHONY : src/client/engine/ecs/Entity.cpp.o

src/client/engine/ecs/Entity.i: src/client/engine/ecs/Entity.cpp.i
.PHONY : src/client/engine/ecs/Entity.i

# target to preprocess a source file
src/client/engine/ecs/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Entity.cpp.i
.PHONY : src/client/engine/ecs/Entity.cpp.i

src/client/engine/ecs/Entity.s: src/client/engine/ecs/Entity.cpp.s
.PHONY : src/client/engine/ecs/Entity.s

# target to generate assembly for a file
src/client/engine/ecs/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Entity.cpp.s
.PHONY : src/client/engine/ecs/Entity.cpp.s

src/client/engine/ecs/EntityManager.o: src/client/engine/ecs/EntityManager.cpp.o
.PHONY : src/client/engine/ecs/EntityManager.o

# target to build an object file
src/client/engine/ecs/EntityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/EntityManager.cpp.o
.PHONY : src/client/engine/ecs/EntityManager.cpp.o

src/client/engine/ecs/EntityManager.i: src/client/engine/ecs/EntityManager.cpp.i
.PHONY : src/client/engine/ecs/EntityManager.i

# target to preprocess a source file
src/client/engine/ecs/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/EntityManager.cpp.i
.PHONY : src/client/engine/ecs/EntityManager.cpp.i

src/client/engine/ecs/EntityManager.s: src/client/engine/ecs/EntityManager.cpp.s
.PHONY : src/client/engine/ecs/EntityManager.s

# target to generate assembly for a file
src/client/engine/ecs/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/EntityManager.cpp.s
.PHONY : src/client/engine/ecs/EntityManager.cpp.s

src/client/engine/ecs/Registry.o: src/client/engine/ecs/Registry.cpp.o
.PHONY : src/client/engine/ecs/Registry.o

# target to build an object file
src/client/engine/ecs/Registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Registry.cpp.o
.PHONY : src/client/engine/ecs/Registry.cpp.o

src/client/engine/ecs/Registry.i: src/client/engine/ecs/Registry.cpp.i
.PHONY : src/client/engine/ecs/Registry.i

# target to preprocess a source file
src/client/engine/ecs/Registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Registry.cpp.i
.PHONY : src/client/engine/ecs/Registry.cpp.i

src/client/engine/ecs/Registry.s: src/client/engine/ecs/Registry.cpp.s
.PHONY : src/client/engine/ecs/Registry.s

# target to generate assembly for a file
src/client/engine/ecs/Registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/Registry.cpp.s
.PHONY : src/client/engine/ecs/Registry.cpp.s

src/client/engine/ecs/System.o: src/client/engine/ecs/System.cpp.o
.PHONY : src/client/engine/ecs/System.o

# target to build an object file
src/client/engine/ecs/System.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/System.cpp.o
.PHONY : src/client/engine/ecs/System.cpp.o

src/client/engine/ecs/System.i: src/client/engine/ecs/System.cpp.i
.PHONY : src/client/engine/ecs/System.i

# target to preprocess a source file
src/client/engine/ecs/System.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/System.cpp.i
.PHONY : src/client/engine/ecs/System.cpp.i

src/client/engine/ecs/System.s: src/client/engine/ecs/System.cpp.s
.PHONY : src/client/engine/ecs/System.s

# target to generate assembly for a file
src/client/engine/ecs/System.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/engine/ecs/System.cpp.s
.PHONY : src/client/engine/ecs/System.cpp.s

src/server/server.o: src/server/server.cpp.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/server.cpp.o
.PHONY : src/server/server.cpp.o

src/server/server.i: src/server/server.cpp.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/server.cpp.i
.PHONY : src/server/server.cpp.i

src/server/server.s: src/server/server.cpp.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/server.cpp.s
.PHONY : src/server/server.cpp.s

src/shared/shared.o: src/shared/shared.cpp.o
.PHONY : src/shared/shared.o

# target to build an object file
src/shared/shared.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_rtype.dir/build.make CMakeFiles/shared_rtype.dir/src/shared/shared.cpp.o
.PHONY : src/shared/shared.cpp.o

src/shared/shared.i: src/shared/shared.cpp.i
.PHONY : src/shared/shared.i

# target to preprocess a source file
src/shared/shared.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_rtype.dir/build.make CMakeFiles/shared_rtype.dir/src/shared/shared.cpp.i
.PHONY : src/shared/shared.cpp.i

src/shared/shared.s: src/shared/shared.cpp.s
.PHONY : src/shared/shared.s

# target to generate assembly for a file
src/shared/shared.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_rtype.dir/build.make CMakeFiles/shared_rtype.dir/src/shared/shared.cpp.s
.PHONY : src/shared/shared.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... r-type_client"
	@echo "... r-type_server"
	@echo "... shared_rtype"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/client/engine/ecs/ComponentSparseArray.o"
	@echo "... src/client/engine/ecs/ComponentSparseArray.i"
	@echo "... src/client/engine/ecs/ComponentSparseArray.s"
	@echo "... src/client/engine/ecs/Core.o"
	@echo "... src/client/engine/ecs/Core.i"
	@echo "... src/client/engine/ecs/Core.s"
	@echo "... src/client/engine/ecs/Entity.o"
	@echo "... src/client/engine/ecs/Entity.i"
	@echo "... src/client/engine/ecs/Entity.s"
	@echo "... src/client/engine/ecs/EntityManager.o"
	@echo "... src/client/engine/ecs/EntityManager.i"
	@echo "... src/client/engine/ecs/EntityManager.s"
	@echo "... src/client/engine/ecs/Registry.o"
	@echo "... src/client/engine/ecs/Registry.i"
	@echo "... src/client/engine/ecs/Registry.s"
	@echo "... src/client/engine/ecs/System.o"
	@echo "... src/client/engine/ecs/System.i"
	@echo "... src/client/engine/ecs/System.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/shared/shared.o"
	@echo "... src/shared/shared.i"
	@echo "... src/shared/shared.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

